name: Auto Close Test Issues
on:
  issues:
    types: [opened]

jobs:
  close-test:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, 'test') || contains(github.event.issue.body, 'test')
    permissions:
      issues: write
    steps:
      - name: Close Issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ISSUE: ${{ github.event.issue.number }}
        run: |
          gh issue edit "$ISSUE" --add-label "spam" && gh issue close "$ISSUE" -c "Closing automatically because this appears to be a test issue." -r "not planned"
